### ISSUE TITLE
[background-img]

### ISSUE THREAD

**Issue by danielvan** [23d1/Modul#1]
Would be good to be able to use background-imgs on the full row. If I add it manually, it is still not 100% as it is limited by the padding on the container-fluid element.

![screen shot 2017-02-07 at 23 08 49](https://cloud.githubusercontent.com/assets/5878523/22715774/74d7ecde-ed8a-11e6-83eb-b206ab0f542b.png)

**Comment by 23d1** [comment]
Coming in Beta 1. 💯

**Comment by 23d1** [comment]
Done in the latest update.
